# Generated by Django 4.2.8 on 2026-03-26 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('character', models.CharField(help_text='Malayalam character name', max_length=100)),
                ('place', models.CharField(help_text='Malayalam place name', max_length=100)),
                ('theme', models.CharField(help_text='Story theme (e.g., friendship, kindness)', max_length=100)),
                ('story_text', models.TextField(help_text='Generated story content')),
                ('story_history', models.JSONField(default=list, help_text='List of story parts for context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story Session',
                'verbose_name_plural': 'Story Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
